//! Integration tests for `bistec_architect::docs` (AC-6, parsing part).
//!
//! Fixtures live in `tests/fixtures/docs/` and are generated by
//! `tests/fixtures/docs/make_fixtures.py` (Python stdlib only).

use std::path::PathBuf;

use bistec_architect::docs::{
    estimate_tokens, parse_bytes, parse_document, total_tokens, DocError, Section,
    TARGET_SECTION_TOKENS,
};

fn fixture_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/docs").join(name)
}

/// ids are `S1..Sn`, contiguous, in order, and every section has non-empty text.
fn assert_contiguous_nonempty(sections: &[Section]) {
    assert!(!sections.is_empty(), "expected at least one section");
    for (i, s) in sections.iter().enumerate() {
        assert_eq!(s.id, format!("S{}", i + 1), "section id out of order");
        assert!(!s.text.trim().is_empty(), "section {} has blank text", s.id);
        assert_eq!(s.tokens, estimate_tokens(&s.text));
    }
}

#[test]
fn estimate_tokens_matches_spec_example() {
    assert_eq!(estimate_tokens("abcde"), 2);
}

#[test]
fn pdf_with_text_layer_parses_into_sections() {
    let sections = parse_document(&fixture_path("sample.pdf")).expect("sample.pdf should parse");
    assert_contiguous_nonempty(&sections);
}

#[test]
fn docx_parses_and_captures_headings() {
    let sections = parse_document(&fixture_path("sample.docx")).expect("sample.docx should parse");
    assert_contiguous_nonempty(&sections);

    let headings: Vec<&str> = sections.iter().filter_map(|s| s.heading.as_deref()).collect();
    assert!(
        headings.iter().any(|h| h.eq_ignore_ascii_case("Overview")),
        "expected an Overview heading, got {headings:?}"
    );
    assert!(
        headings.iter().any(|h| h.eq_ignore_ascii_case("Authentication")),
        "expected an Authentication heading, got {headings:?}"
    );
}

#[test]
fn markdown_splits_at_atx_headings() {
    let sections = parse_document(&fixture_path("sample.md")).expect("sample.md should parse");
    assert_contiguous_nonempty(&sections);

    let headings: Vec<&str> = sections.iter().filter_map(|s| s.heading.as_deref()).collect();
    assert!(headings.contains(&"Compliance"), "expected a Compliance heading, got {headings:?}");
    assert!(
        headings.contains(&"Non-Functional Requirements"),
        "expected a Non-Functional Requirements heading, got {headings:?}"
    );
}

#[test]
fn txt_parses_into_sections() {
    let sections = parse_document(&fixture_path("sample.txt")).expect("sample.txt should parse");
    assert_contiguous_nonempty(&sections);
    // Plain text has no headings.
    assert!(sections.iter().all(|s| s.heading.is_none()));
}

#[test]
fn scanned_pdf_with_no_text_layer_is_rejected() {
    let err = parse_document(&fixture_path("scanned.pdf")).expect_err("scanned.pdf has no text layer");
    assert!(matches!(err, DocError::NoTextLayer));
    assert_eq!(
        err.to_string(),
        "This PDF has no text layer (OCR is not supported in v1)"
    );
}

#[test]
fn unsupported_extension_is_rejected() {
    let err = parse_bytes("report.rtf", b"whatever content").expect_err("rtf is unsupported");
    match err {
        DocError::Unsupported(ext) => assert_eq!(ext, "rtf"),
        other => panic!("expected Unsupported, got {other:?}"),
    }
}

#[test]
fn large_markdown_exceeds_twenty_thousand_tokens() {
    let sections = parse_document(&fixture_path("large.md")).expect("large.md should parse");
    assert_contiguous_nonempty(&sections);
    assert!(
        total_tokens(&sections) > 20_000,
        "expected large.md to exceed 20,000 estimated tokens, got {}",
        total_tokens(&sections)
    );
}

/// A single oversized text block (no blank lines, forcing sentence-boundary
/// splitting) must come back as multiple sections, none more than ~1.2x
/// `TARGET_SECTION_TOKENS`, with continuation headings on every section
/// after the first.
#[test]
fn oversized_section_is_split_and_bounded() {
    let sentence = "The insurer portal must handle this requirement reliably for every registered user. ";
    let mut long_text = String::from("# Big Requirement\n\n");
    // Each sentence is ~22 tokens; repeat well past TARGET_SECTION_TOKENS.
    for _ in 0..500 {
        long_text.push_str(sentence);
    }

    let sections = parse_bytes("big.md", long_text.as_bytes()).expect("should parse");
    assert_contiguous_nonempty(&sections);
    assert!(sections.len() > 1, "expected the oversized section to be split");

    let max_allowed = (TARGET_SECTION_TOKENS as f64 * 1.2) as usize;
    for s in &sections {
        assert!(
            s.tokens <= max_allowed,
            "section {} has {} tokens, exceeding {}x target ({})",
            s.id,
            s.tokens,
            1.2,
            max_allowed
        );
    }

    assert_eq!(sections[0].heading.as_deref(), Some("Big Requirement"));
    for s in &sections[1..] {
        assert_eq!(s.heading.as_deref(), Some("Big Requirement (cont.)"));
    }
}

#[test]
fn empty_document_is_empty_error() {
    let err = parse_bytes("blank.txt", b"   \n\n\t\n").expect_err("blank content should be Empty");
    assert!(matches!(err, DocError::Empty));
}
